/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/
#include "types.h"
#include "GPIO.h"
#include "RCC.h"
#include "BasicTIM.h"
#include "Pwr.h"
#include "TIM15.h"
#include "SignalGen.h"
#include "Utilities.h"
#include "MelodyPlayer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32 Tick;

void Blink(void)
{
	GPIO_Toggle(PORT_B, 13);
}

void TickHandler(void)
{
	Tick++;
	Blink();
}

uint32 GetTicks(void)
{
	return Tick;
}

int main(void)
{	RCC_ClockEnable(RCC_GPIOA);
	RCC_ClockEnable(RCC_GPIOB);
	RCC_ClockEnable(RCC_GPIOC);
	RCC_ClockEnable(RCC_TIM6);
	RCC_ClockEnable(RCC_PWR);
	RCC_ClockEnable(RCC_FLASH);
	RCC_ClockEnable(RCC_TIM2);
	RCC_ClockEnable(RCC_DMA1);

	Pwr_SetVoltageRange(Range_2);
	Pwr_SetVoltageRange(Range_1);

	RCC_ClockSet(80000000);
	BasicTIM_Set(TIM6,TickHandler);

	GPIO_Set(PORT_A, 5, GPIO_OUTPUT|GPIO_OTYPE_PP|GPIO_OSPEED_MS);
	GPIO_Set(PORT_B, 13, GPIO_OUTPUT|GPIO_OTYPE_PP|GPIO_OSPEED_MS);
	GPIO_Set(PORT_C, 13, GPIO_INPUT);

	GPIO_Set(PORT_A, 0, GPIO_ALT1|GPIO_OTYPE_PP|GPIO_OSPEED_VHS);//TIM15_CH1
	GPIO_Set(PORT_A, 1, GPIO_ALT1|GPIO_OTYPE_PP|GPIO_OSPEED_VHS);//TIM15_CH2

	SignalGen_Init();

	dtMusicNoteDesc notes[] = {
			{ .MusicNote = C4, .Beat = Ti},
			{ .MusicNote = E4, .Beat = Ti},
			{ .MusicNote = C4, .Beat = Ti},
			{ .MusicNote = E4, .Beat = Ti},
			{ .MusicNote = G4, .Beat = Ta},
			{ .MusicNote = G4, .Beat = Ta},
			{ .MusicNote = C4, .Beat = Ti},
			{ .MusicNote = E4, .Beat = Ti},
			{ .MusicNote = C4, .Beat = Ti},
			{ .MusicNote = E4, .Beat = Ti},
			{ .MusicNote = G4, .Beat = Ta},
			{ .MusicNote = G4, .Beat = Ta},
			{ .MusicNote = C5, .Beat = Ti},
			{ .MusicNote = B4, .Beat = Ti},
			{ .MusicNote = A4, .Beat = Ti},
			{ .MusicNote = G4, .Beat = Ti},
			{ .MusicNote = F4, .Beat = Ta},
			{ .MusicNote = A4, .Beat = Ta},
			{ .MusicNote = G4, .Beat = Ti},
			{ .MusicNote = F4, .Beat = Ti},
			{ .MusicNote = E4, .Beat = Ti},
			{ .MusicNote = D4, .Beat = Ti},
			{ .MusicNote = C4, .Beat = Ta},
			{ .MusicNote = C4, .Beat = Ta},
	};
	dtMelody melody = {.Length = sizeof(notes), .beat = 5, .Notes = notes};

	MelodyPlayer_Start(melody);

	GPIO_Write(PORT_A, 5, 1);
	GPIO_Write(PORT_A, 5, 0);
	GPIO_Write(PORT_B, 13, 0);

	for(;;)
	{
		MelodyPlayer_Task();
		if(GPIO_Read(PORT_C, 13))
		{
			GPIO_Write(PORT_A, 5, 1);
		}
		else
		{
			SignalGen_Stop();
			GPIO_Write(PORT_A, 5, 0);
		}

	}
}
